version: "3.9"
services:

  traefik:
    ports:
      - "8080:8080"
      - "80:80"
    command:
      - --api
      - --api.insecure=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --accesslog
      - --log
      - --entrypoints.web.address=:80

  pgadmin:
    ports:
      - "5050:5050"
    expose:
      - "5050"

  db:
    volumes:
      - app-db-data-dev:${PGDATA}
      - ./database/pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./backend:/code
      - ~/.cache.pypoetry:/root/.cache/pypoetry

  webapp:
    ports:
      - "3000:80"
    expose:
      - "80"

  orthanc:
    expose:
      - "8042"
    volumes:
      # configuration file
      - ${ORTHANC_CONFIG}:${ORTHANC_CONFIG_INTERNAL}:ro
      # storage volume for raw dicoms
      - pacs-data-dev:${ORTHANC_DICOM_DATA_INTERNAL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.orthanc.entrypoints=web
      - traefik.http.routers.orthanc.rule=PathPrefix(`/pacs`)
      - traefik.http.routers.orthanc.priority=10
      - traefik.http.routers.orthanc.tls=false

      - traefik.http.middlewares.cors-allow.headers.accesscontrolallowmethods=*
      - traefik.http.middlewares.cors-allow.headers.accesscontrolalloworiginlist=*
      - traefik.http.middlewares.cors-allow.headers.accesscontrolallowheaders=*
      - traefik.http.middlewares.cors-allow.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.cors-allow.headers.addvaryheader=true

      - traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/pacs

      - traefik.http.routers.orthanc.middlewares=cors-allow,strip-prefix

volumes:
  app-db-data-dev:
  pacs-data-dev:
