version: "3.9"
services:

  traefik:
    ports:
      - "8080:8080"
      - "80:80"
    command:
      - --api
      - --api.insecure=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --accesslog
      - --log
      - --entrypoints.web-secure.address=:443

  pgadmin:
    ports:
      - "5050:5050"
    expose:
      - "5050"

  db:
    volumes:
      - app-db-data-dev:${PGDATA}
      - ./database/pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5678:5678"
    volumes:
      - ./backend:/code
    labels:
      - traefik.http.services.backend.loadbalancer.server.port=8000
    tty: true

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile.dev
    expose:
      - "3000"
    volumes:
      - ./webapp:/code
    labels:
      - traefik.http.services.webapp.loadbalancer.server.port=3000
    tty: true

  orthanc:
    labels:
      - traefik.http.middlewares.cors-allow.headers.accesscontrolalloworiginlist=*

volumes:
  app-db-data-dev:
  pacs-data-dev:
