const colorMaps = {
  twoHot: '2hot',
  asymmtricalEarthTones: 'Asymmtrical Earth Tones (6_21b)',
  blueWhite: 'BLUE-WHITE',
  bkBu: 'BkBu',
  bkCy: 'BkCy',
  bkGn: 'BkGn',
  bkMa: 'BkMa',
  bkRd: 'BkRd',
  blackBlueWhite: 'Black, Blue and White',
  blackOrangeWhite: 'Black, Orange and White',
  blackBodyRadiation: 'Black-Body Radiation',
  blueToRedRainbow: 'Blue to Red Rainbow',
  blueToYellow: 'Blue to Yellow',
  blues: 'Blues',
  brBG: 'BrBG',
  brOrYl: 'BrOrYl',
  buGn: 'BuGn',
  buGnYl: 'BuGnYl',
  buPu: 'BuPu',
  buRd: 'BuRd',
  cIELabBlueToRed: 'CIELab Blue to Red',
  cIELabBlue2Red: 'CIELab_blue2red',
  coldAndHot: 'Cold and Hot',
  coolToWarm: 'Cool to Warm',
  coolToWarmExtended: 'Cool to Warm (Extended)',
  gBBr: 'GBBr',
  greenWhiteLinear: 'GREEN-WHITE_LINEAR',
  gYPi: 'GYPi',
  gnBu: 'GnBu',
  gnBuPu: 'GnBuPu',
  gnRP: 'GnRP',
  gnYlRd: 'GnYlRd',
  grayscale: 'Grayscale',
  greenBlueAsymmetricDivergent: 'Green-Blue Asymmetric Divergent (62Blbc)',
  greens: 'Greens',
  gyRd: 'GyRd',
  haze: 'Haze',
  hazeCyan: 'Haze_cyan',
  hazeGreen: 'Haze_green',
  hazeLime: 'Haze_lime',
  infernoMatplotlib: 'Inferno (matplotlib)',
  linearBlue: 'Linear Blue (8_31f)',
  linearYGB: 'Linear YGB 1211g',
  magmaMatplotlib: 'Magma (matplotlib)',
  mutedBlueGreen: 'Muted Blue-Green',
  orPu: 'OrPu',
  oranges: 'Oranges',
  pRGn: 'PRGn',
  piYG: 'PiYG',
  plasmaMatplotlib: 'Plasma (matplotlib)',
  puBu: 'PuBu',
  puOr: 'PuOr',
  puRd: 'PuRd',
  purples: 'Purples',
  redPurple: 'RED-PURPLE',
  redTemperature: 'RED_TEMPERATURE',
  rainbowBlendedBlack: 'Rainbow Blended Black',
  rainbowBlendedGrey: 'Rainbow Blended Grey',
  rainbowBlendedWhite: 'Rainbow Blended White',
  rainbowDesaturated: 'Rainbow Desaturated',
  rdOr: 'RdOr',
  rdOrYl: 'RdOrYl',
  rdPu: 'RdPu',
  redToBlueRainbow: 'Red to Blue Rainbow',
  reds: 'Reds',
  spectralLowBlue: 'Spectral_lowBlue',
  viridisMatplotlib: 'Viridis (matplotlib)',
  warmToCool: 'Warm to Cool',
  warmToCoolExtended: 'Warm to Cool (Extended)',
  xRay: 'X Ray',
  yellow15: 'Yellow 15',
  blot: 'blot',
  blue2Cyan: 'blue2cyan',
  blue2Yellow: 'blue2yellow',
  boneMatlab: 'bone_Matlab',
  coolWarm: 'coolwarm',
  copperMatlab: 'copper_Matlab',
  erdcBlue2CyanBW: 'erdc_blue2cyan_BW',
  erdcBlue2Gold: 'erdc_blue2gold',
  erdcBlue2GoldBW: 'erdc_blue2gold_BW',
  erdcBlue2GreenBW: 'erdc_blue2green_BW',
  erdcBlue2GreenMuted: 'erdc_blue2green_muted',
  erdcBlue2Yellow: 'erdc_blue2yellow',
  erdcBlueBW: 'erdc_blue_BW',
  erdcBrownBW: 'erdc_brown_BW',
  erdcCyan2Orange: 'erdc_cyan2orange',
  erdcDivHiPurpleGreen: 'erdc_divHi_purpleGreen',
  erdcDivHiPurpleGreenDim: 'erdc_divHi_purpleGreen_dim',
  erdcDivLowIcePeach: 'erdc_divLow_icePeach',
  erdcDivLowPurpleGreen: 'erdc_divLow_purpleGreen',
  erdcGoldBW: 'erdc_gold_BW',
  erdcGreen2YellowBW: 'erdc_green2yellow_BW',
  erdcIceFireH: 'erdc_iceFire_H',
  erdcIceFireL: 'erdc_iceFire_L',
  erdcMagentaBW: 'erdc_magenta_BW',
  erdcMarine2GoldBW: 'erdc_marine2gold_BW',
  erdcOrangeBW: 'erdc_orange_BW',
  erdcPbjLin: 'erdc_pbj_lin',
  erdcPurple2Green: 'erdc_purple2green',
  erdcPurple2GreenDark: 'erdc_purple2green_dark',
  erdcPurple2PinkBW: 'erdc_purple2pink_BW',
  erdcPurpleBW: 'erdc_purple_BW',
  erdcRainbowBright: 'erdc_rainbow_bright',
  erdcRainbowDark: 'erdc_rainbow_dark',
  erdcRed2PurpleBW: 'erdc_red2purple_BW',
  erdcRed2YellowBW: 'erdc_red2yellow_BW',
  erdcRedBW: 'erdc_red_BW',
  erdcSapphire2GoldBW: 'erdc_sapphire2gold_BW',
  gistEarth: 'gist_earth',
  grayMatlab: 'gray_Matlab',
  heatedObject: 'heated_object',
  hsv: 'hsv',
  hueL60: 'hue_L60',
  jet: 'jet',
  magenta: 'magenta',
  nicCubicL: 'nic_CubicL',
  nicCubicYF: 'nic_CubicYF',
  nicEdge: 'nic_Edge',
  pinkMatlab: 'pink_Matlab',
  rainbow: 'rainbow'
};

export default colorMaps;
